# Generated by Django 4.1.1 on 2022-10-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='untirta',
            name='Dosen',
        ),
        migrations.RemoveField(
            model_name='untirta',
            name='Mahasiswa',
        ),
        migrations.RemoveField(
            model_name='untirta',
            name='Staf',
        ),
        migrations.DeleteModel(
            name='Dosen',
        ),
        migrations.DeleteModel(
            name='Mahasiswa',
        ),
        migrations.DeleteModel(
            name='Staf',
        ),
        migrations.DeleteModel(
            name='untirta',
        ),
    ]
